name: Lambdas Dev

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'
      - 'lambdas/env/dev/**'
      - '.github/workflows/lambdas-dev.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'lambda/**'
      - 'lambdas/env/dev/**'
      - '.github/workflows/lambdas-dev.yml'

jobs:
  deploy:
    name: Deploy Lambdas to Dev
    uses: ./.github/workflows/terraform-deploy-reusable.yml
    with:
      terraform-version: '1.5.0'
      aws-region: 'us-east-1'
      working-directory: 'lambdas'
      tfvars-file: 'env/dev/dev.tfvars'
      environment: 'dev'
      enable-servicenow: true
      servicenow-deployment-gate: '{"environment":"dev","jobName":"Terraform Apply"}'
      artifact-retention-days: 7
      run-apply: true
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      sn-devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
      sn-instance-url: ${{ secrets.SN_INSTANCE_URL }}
      sn-orchestration-tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
